const express = require("express");
const router = express.Router();
const controller = require('./controller')
const validations = require('./validations')
const { verifyToken } = require('../../middlewares')
router.get('/dashboard', [verifyToken], (req, res) => controller.dashboard(req, res));
router.get('/list', [verifyToken], (req, res) => controller.list(req, res));
router.get('/history', [verifyToken], (req, res) => controller.history(req, res));
router.get('/details/:id', [verifyToken], (req, res) => controller.details(req, res));
router.post('/create', [verifyToken, validations.create], (req, res) => controller.create(req, res));
router.patch('/update/:id', [verifyToken, validations.create], (req, res) => controller.update(req, res));
router.delete('/delete/:id', [verifyToken], (req, res) => controller.delete(req, res));
router.post('/restore/:id', [verifyToken], (req, res) => controller.restore(req, res));
router.patch('/assign-asset/:id', [verifyToken, validations.assignAsset], (req, res) => controller.assignAsset(req, res));
router.patch('/return-asset/:id', [verifyToken, validations.returnAsset], (req, res) => controller.returnAsset(req, res));
router.patch('/change-status/:id', [verifyToken, validations.changeStatus], (req, res) => controller.changeStatus(req, res));
module.exports = router;
